name: Update Instagram Posts

on:
  schedule:
    - cron: '0 0 * * *' # 毎日日本時間午前9時に実行
  workflow_dispatch: # 手動実行も可能にする

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install instaloader

      - name: Run script
        run: python your_script_name.py # Pythonファイル名を指定

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts.json
          git commit -m "Update latest posts" || exit 0
          git push
